Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.boot_timeout = 300

  # VM 1 
  config.vm.define :vm1 do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "192.168.22.3"

    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
    vm1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y ansible
    SHELL
  end

  # VM 2
  config.vm.define :vm2 do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.22.4"

    vm2.vm.network "forwarded_port", guest: 19999, host: 19999

    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
    end
  end
end
