name: Build Image
on:
  push:
    branches:
    - main
    - 'infra/**'
    
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v6
    - name: Build Docker image
      run: |
        docker build -t gc2-api-image .