name: pull request test Node.js CI
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clonando repositório
      uses: actions/checkout@v6
    - name: versão do node
      uses: actions/setup-node@v6
      with:
        node-version: '>=21'
    - name: instalando dependências
      run: npm install
    - name: Executando a aplicação
      run: |
        node index.js &
        sleep 5
        kill $!