name: push test Node.js CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: clonando repositório
      uses: actions/checkout@v6
    - name: versão do node
      uses: actions/setup-node@v6
      with:
        node-version: '>=21'
    - name: instalando dependências
      run: npm install